server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password
          url: jdbc:h2:mem:test;
          driverClassName: org.h2.Driver
          username: sa
          password: password
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

logging.level:
  org.springframework.security: trace

logging:
  file:
    path: "src/logs"

date:
  zone: 'Pacific/Auckland'

client:
  domain: 'http://localhost:4201/'

authenticate:
    path:
      - "/admin/view-next"
      - "/admin/delete"
      - "/admin/logout"

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: 604800000

recaptcha:
  path: "/recaptcha"
  projectID: "mr-grass-master-v3"
  key:
    login: "6LdYASEqAAAAAGS0xlyDWNlHa9FRxrFNMcmejVTb"
    contactForm: "6LdYASEqAAAAAGS0xlyDWNlHa9FRxrFNMcmejVTb"
