server:
  port: 8080

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password
          url: jdbc:h2:mem:test;
          driverClassName: org.h2.Driver
          username: sa
          password: password

  jpa:
    open-in-view: false

  sql:
    init:
      mode: always

  jackson:
    parser:
      allow-numeric-leading-zeros: true

logging.level:
  org.springframework.security: trace

logging:
  file:
    path: "src/logs"

date:
  zone: "Pacific/Auckland"

authenticate:
  path:
    - "/admin/view-next"
    - "/admin/delete"
    - "/admin/logout"

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: 604800000

client:
  domain: "http://localhost"
  request-url: 'localhost'

recaptcha:
  path: "/recaptcha"
  projectID: "mr-grass-master-v3"
  key:
    login: "6LdYASEqAAAAAGS0xlyDWNlHa9FRxrFNMcmejVTb"
    contactForm: "6LdYASEqAAAAAGS0xlyDWNlHa9FRxrFNMcmejVTb"

