server:
    port: 8080

spring:
    datasource:
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#        password: password
        url: jdbc:h2:mem:test;
        driverClassName: org.h2.Driver
        username: sa
        password: password

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create

    sql:
        init:
            mode: always

    thymeleaf:
        servlet:
            produce-partial-output-while-processing: false

logging.level:
    org.springframework.security: TRACE

logging:
    file:
        path: "src/logs"

date:
    zone: 'Pacific/Auckland'

