server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password
#        url: jdbc:h2:mem:test;
#        driverClassName: org.h2.Driver
#        username: sa
#        password: password
    sql:
      init:
        mode: always

    thymeleaf:
        servlet:
            produce-partial-output-while-processing: false

database:
    embedded: false

logging.level:
    org.springframework.security: trace

logging:
    file:
        path: "src/logs"

date:
    zone: 'Pacific/Auckland'

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: 604800000

