DROP TABLE IF EXISTS CONTACT;

CREATE TABLE IF NOT EXISTS CONTACT
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME       VARCHAR(50) NOT NULL,
    LAST_NAME        VARCHAR(50),
    EMAIL            VARCHAR(50) NOT NULL,
    PHONE            VARCHAR(50),
    ADDRESS_LINE1    VARCHAR(50) NOT NULL,
    ADDRESS_LINE2    VARCHAR(50) NOT NULL,
    ADDRESS_LINE3    VARCHAR(50) NOT NULL,
    MESSAGE          CLOB(10K)  NOT NULL,
    INSERT_DATE_TIME TIMESTAMP
);

-- Security
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS AUTHORITIES;

CREATE TABLE IF NOT EXISTS USERS
(
    USERNAME VARCHAR(128) PRIMARY KEY,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    USERNAME  VARCHAR(128) NOT NULL,
    AUTHORITY VARCHAR(128) NOT NULL
);

ALTER TABLE AUTHORITIES DROP CONSTRAINT IF EXISTS AUTHORITIES_UNIQUE;
ALTER TABLE AUTHORITIES DROP CONSTRAINT IF EXISTS AUTHORITIES_FK1;

ALTER TABLE AUTHORITIES
    ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES
    ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);
